usds/ditap-curriculum-update

curriculum/overviewandmap.md

Do a straight conversion from EdX page to .md. This is a really ugly and difficult page. It will need dramatic refactoring. However, this is just the beginning of the process of moving data from it's existing locations to this repo.
Assigning to @farooqzakhilwal  and @april-cruz  for review.

Add curriculum folder and convert overview doc to .md format

---

.github/workflows/action.yml

Add github action to check for valid URL links on each code push

---

3_Curriculum/3B_Ditap-Core-Curriculum/3B.1-Course-Modules/Module-1/Sprint-2/Digital Service Methods, Roles, and Sources of Supply.md

Added sprint 2 Digital Service Methods, Roles, and Sources of Supply.md

Create Digital Service Methods, Roles, and Sources of Supply.md

---

3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 1/Case Study Exercise: Executive Leverage in Digital Transformation.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 1/Digital Teams and Executive Leadership.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 1/Leading High-Performance Digital Teams.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 1/Module One Outline.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 1/Strategic Contracting for Digital Transformation.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 1/The Digital Transformation Imperative.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 2/Case Study Exercise: Strategic Product Vision for Impact.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 2/Human-Centered Design as Strategic Imperative.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 2/Module Two Outline.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 2/Organizational Readiness Assessment for Digital Transformation.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 2/Strategic Market Research for Digital Services.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-Curriculum/Module 2/Strategic Product Vision Development.md

I'm new to pull requests and am trying this out. I created a fork of the main repo and added all of Module 1 to the fork. This way you don't need to approve a pull request for every file I upload. 
(Crossing my fingers and hoping I'm doing this right.)

Add Modules 1 and 2 to DITAP Strategy for Executive Leaders

---

3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/DITAP SEL Facilitator Guide.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/DITAP Strategy for Executive Leaders Course Playbook.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 3/Advanced Contract Language for Digital Services.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 3/Case Study Exercise: Leading Through Risk.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 3/Legal Sufficiency vs. Risk Aversion.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 3/Modern Contract Types for Digital Services.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 3/Module Three Outline.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 3/Translating User Needs into Acquisition Language.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 4/Avoiding Bias in Vendor Evaluations.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 4/Case Study Exercise: Recognizing and Reducing Bias in Evaluations.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 4/Early and Open Vendor Engagement.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 4/Legal Sufficiency and Risk Aversion Strategies.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 4/Module Four Outline.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 4/Strategic Evaluation of Digital Services Vendors.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 5/Calculating Delayed Decision Costs.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 5/Case Study Exercise: Change Management Starts at the Top.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 5/Influencing Agency Decisions.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 5/Module Five Outline.md
3_Curriculum/3C_Ditap-Adaptation-Curriculum/3C.2_Ditap-Strategy-For-Executive-Leaders-Curriculum/Module 5/Using Storytelling to Influence.md

This is adding the remaining modules to DITAP Strategy for Executive Leaders as well as 2 other files to that folder.

Add Modules 3, 4, and 5 to DITAP Strategy for Executive Leaders

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 3/Class Activity: Estimating the Cost of Agile Delivery.md

Added the IGCE Tool to Course materials in Module 0

Add IGCE Tool

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-5/Sprint-2/Continuous Improvement and Scalable Practices.md

Update Continuous Improvement and Scalable Practices.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-4/Sprint-4/Contract Management and Problem Resolution.md

Update Contract Management and Problem Resolution.md link

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/Sprint-4/Conducting Effective Market Research.md

Update Conducting Effective Market Research.md - cots

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/Sprint-2/Developing the Solicitation.md

Update Developing the Solicitation.md. spacing issues

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-1/Sprint-1/The Digital Services Landscape.md

Update The Digital Services Landscape.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-1/Sprint-3/Digital Service Tech Bootcamp.md

Update Digital Service Tech Bootcamp.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/Sprint-1/Assessing Agency Readiness.md

Minor changes. Updating "Unit" to "Module"

Update Assessing Agency Readiness.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/Sprint-2/Stakeholder and Customer Mapping.md

Update Stakeholder and Customer Mapping.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/Sprint-3/Defining Success for your Digital Services Acquisition.md

module > sprint - missed this in earlier pull request

Update Defining Success for your Digital Services Acquisition.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/Sprint-3/Running a Successful Evaluation.md

Update Running a Successful Evaluation.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/Sprint-2/Developing the Solicitation.md

Update Developing the Solicitation.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/Sprint-1/Developing a Successful Acquisition Strategy.md

Update Developing a Successful Acquisition Strategy.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-4/Sprint-2/Performance Measurement Under Agile Delivery Contracts.md

Update Performance Measurement Under Agile Delivery Contracts.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-4/Sprint-4/Contract Management and Problem Resolution.md

Update Contract Management and Problem Resolution.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-5/Sprint-1/Leading Change.md

Update Leading Change.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/In-Class-Materials/Activity: Stakeholder Selection and Interview Assignment.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/In-Class-Materials/Assignment: Navigating the Stakeholder Landscape Continued.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/In-Class-Materials/Assignment: Navigating the Stakeholder Landscape.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/In-Class-Materials/Stakeholder Assignment FAQs.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/In-Class-Materials/Stakeholder Assignment Playbook 2025.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/In-Class-Materials/Debriefing Agendas Template.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/In-Class-Materials/Developing a Statement of Objectives Activity.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/In-Class-Materials/Proposed Debriefing Agenda Template.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/In-Class-Materials/Statement of Objectives Template.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/In-Class-Materials/The Power of Debriefing Activity.md

Building out linked Google docs into github documents

Updating Module 2

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 0/Facilitator Guide.md

Update Facilitator Guide.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 1/Understanding Digital Services.md

Update Understanding Digital Services.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 1/Product Thinking and Digital Service Delivery.md

Update Product Thinking and Digital Service Delivery.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 1/Key Roles and Functions of a Digital Service Team.md

Update Key Roles and Functions of a Digital Service Team.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 0/Discovery-Sprint/Define the Problem and Prioritize the User.md

Update Define the Problem and Prioritize the User.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 2/Module Two Outline.md

Update Module Two Outline.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-1/Sprint-3/Digital Service Tech Bootcamp.md

Comment from @edent — Worth mentioning that many OSS projects won't work for free on things like SBOM production? Include provision for paying / sponsoring projects. 
which I think I've covered by suggesting sponsorship.

Update Digital Service Tech Bootcamp.md - consider sponsoring

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 2/Defining the Problem and Understanding the People.md

Update Defining the Problem and Understanding the People.md

---

3_Curriculum/3B_DITAP-Core-Curriculum/Module-1/In-Class-Materials/DITAP Facilitator Guide_Case Study Complete.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-1/In-Class-Materials/Module 1 Sprint 1 DITAP Facilitators Guide_Case Study.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/In-Class-Materials/Module 2 Sprint 1 DITAP Facilitators Guide_Case Study.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-2/In-Class-Materials/Module 2 Sprint 4 DITAP Facilitators Guide_Case Study.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/In-Class-Materials/Module 3 Sprint 1 DITAP Facilitators Guide_Case Study.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/In-Class-Materials/Module 3 Sprint 2 DITAP Facilitators Guide_Case Study.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-3/In-Class-Materials/Module 3 Sprint 3 DITAP Facilitators Guide_Case Study.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-4/In-Class-Materials/Module 4 Sprint 3 DITAP Facilitators Guide_Case Study.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-5/In-Class-Materials/Module_5_DITAP_Facilitators_Guide_Case_Study.md
3_Curriculum/3B_DITAP-Core-Curriculum/Module-5/In-Class-Materials/Module_6_DITAP_Facilitators_Guide_Case_Study_(Wrap_Up).md

Updated case study title across all modules

Case study updates

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 5/Lead by Example.md

Update Lead by Example.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.2_DITAP-Strategy-For-Executive-Leaders-Curriculum/Module 1/Digital Teams and Executive Leadership.md

Update Digital Teams and Executive Leadership.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 4/Module Four Outline.md

Update Module Four Outline.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 3/Module Three Outline.md

Update Module Three Outline.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.2_DITAP-Strategy-For-Executive-Leaders-Curriculum/Module 0/DITAP Strategy for Executive Leaders Course Playbook.md

Update DITAP Strategy for Executive Leaders Course Playbook.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 5/Practicing Product Leadership.md

Update Practicing Product Leadership.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 2/From Insights to Action.md

Update From Insights to Action.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 2/Class Activity: Analyzing User Types and Their Challenges.md

Update Class Activity: Analyzing User Types and Their Challenges.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 3/Artifact: Digital Service Language.md

Update Artifact: Digital Service Language.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 4/Shifting the Mindset: From Compliance to Collaboration.md

Update Shifting the Mindset: From Compliance to Collaboration.md

---

3_Curriculum/3C_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 4/Agile Rituals Meet Federal Oversight.md

Update Agile Rituals Meet Federal Oversight.md

---

3_Curriculum/3A_DITAP-Core-Curriculum/1_Vendor-Materials/Onboarding Kit/Introduction to Threaded Case Study.md

Uploaded the threaded case study video

Create Introduction to Threaded Case Study.md

---

3_Curriculum/3B_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 0/Facilitator Guide.md
3_Curriculum/3B_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 2/Defining the Problem and Understanding the People.md
3_Curriculum/3B_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 3/The Independent Government Cost Estimate (IGCE).md
3_Curriculum/3B_DITAP-Adaptation-Curriculum/3C.1_DITAP-Product-Thinking-And-Acquistions-Curriculum/Module 4/Agile Rituals Meet Federal Oversight.md

Update PM adaptation

---

3_Curriculum/3A_DITAP-Core-Curriculum/Module-0/Self-Paced Materials/1_Program Pre-Assessment.md

Update 1_Program Pre-Assessment.md

---

3_Curriculum/3A_DITAP-Core-Curriculum/Module-4/Sprint-1/Self-Paced Materials/1_Management of Digital Service Delivery.md

Update 1_Management of Digital Service Delivery.md

---

3_Curriculum/3A_DITAP-Core-Curriculum/Module-4/Sprint-4/Self-paced/1_Contract Management and Problem Resolution.md

capitalization, punctuation, header adjustments; one grammatical correction

Update 1_Contract Management and Problem Resolution.md

---

3_Curriculum/3A_DITAP-Core-Curriculum/Module-4/Sprint-3/Self-Paced Materials/1_Contract Kickoff.md

Update 1_Contract Kickoff.md

---

3_Curriculum/3A_DITAP-Core-Curriculum/Module-0/Self-Paced Materials/2_Orientation.md
3_Curriculum/3A_DITAP-Core-Curriculum/Module-1/Sprint-1/Self-Paced Materials/1_The Digital Services Landscape.md
3_Curriculum/3A_DITAP-Core-Curriculum/Module-1/Sprint-2/Self-Paced Materials/1_Digital Service Methods, Roles, and Sources of Supply.md
3_Curriculum/3A_DITAP-Core-Curriculum/Module-1/Sprint-3/Self-Paced Materials/1_Digital Service Tech Bootcamp.md
3_Curriculum/3A_DITAP-Core-Curriculum/Module-2/Sprint-1/Self-Paced Materials/1_Assessing Agency Readiness.md
3_Curriculum/3A_DITAP-Core-Curriculum/Module-2/Sprint-2/Self-Paced Materials/1_Stakeholder and Customer Mapping.md
3_Curriculum/3A_DITAP-Core-Curriculum/Module-2/Sprint-3/Self-Paced Materials/1_Defining Success for your Digital Services Acquisition.md
3_Curriculum/3A_DITAP-Core-Curriculum/Module-2/Sprint-4/Self-Paced Materials/Self-Paced Materials/1_Conducting Effective Market Research.md
3_Curriculum/3A_DITAP-Core-Curriculum/Module-3/Sprint-1/Self-Paced Materials/1_Developing a Successful Acquisition Strategy.md
3_Curriculum/3A_DITAP-Core-Curriculum/Module-3/Sprint-2/Self-Paced Materials/1_Developing the Solicitation.md
3_Curriculum/3A_DITAP-Core-Curriculum/Module-3/Sprint-3/Self-Paced Materials/1_Running a Successful Evaluation.md

Updating h1s and other headings formatting

Updating h1s

---

3_Curriculum/3A_DITAP-Core-Curriculum/1_Vendor-Materials/Live Digital Assignment (LDA)/LDA Guidance.md
3_Curriculum/3A_DITAP-Core-Curriculum/1_Vendor-Materials/Live Digital Assignment (LDA)/LDA Phase 4: Final Team Reflections.md
3_Curriculum/3A_DITAP-Core-Curriculum/1_Vendor-Materials/Live Digital Assignment (LDA)/LDA Vendor Evaluation.md

Updating LDA

---

3_Curriculum/3A_DITAP-Core-Curriculum/1_Vendor-Materials/Case Study: Threaded Case Scenario/Core Case Study: Facilitator Guide.md

Added introduction explanation

Update Core Case Study: Facilitator Guide.md

---

3_Curriculum/3A_DITAP-Core-Curriculum/1_Vendor-Materials/Onboarding Kit/Pre-Program Survey.md

Update Pre-Program Survey.md

---

3_Curriculum/3A_DITAP-Core-Curriculum/1_Vendor-Materials/SCORM Files/SCORM Package Repository - Read Me.md

Provide updated guidance to vendors on how to access latest SCORM packages.

Update SCORM Package Repository - Read Me.md
